<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Patra Logistik (2)</name>
   <tag></tag>
   <elementGuidId>28ffc681-774b-4a6f-8944-2e52d462283a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='sidebar']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sidebar >> internal:text=&quot;Patra Logistik&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d30b47e4-4cd0-47fe-aa4a-f817fa6884a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-light</value>
      <webElementGuid>d20e4ed3-1f5e-4350-b318-5d20a7e3933f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Patra Logistik</value>
      <webElementGuid>e247eea2-1241-4fb4-a8b9-2553c684bd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;main-sidebar-header&quot;]/div[@class=&quot;text-light&quot;]</value>
      <webElementGuid>f774958f-6e5e-4b7a-a942-2cd0b3488e94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='sidebar']/div/div</value>
      <webElementGuid>61f490f8-9e0c-47c4-b43d-39e6e473fd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patlog Manajemen'])[1]/following::div[2]</value>
      <webElementGuid>5310cfc6-f117-42e2-89b0-2afe91053d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::div[4]</value>
      <webElementGuid>7ebeb176-b110-4d87-a976-d1ef31cb8d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview'])[1]/preceding::div[4]</value>
      <webElementGuid>ee1e5f09-c5e9-4c53-b75e-0fa33779824d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div</value>
      <webElementGuid>551417df-83f1-4655-9d23-5c381b0b90c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Patra Logistik' or . = 'Patra Logistik')]</value>
      <webElementGuid>309b6078-092f-4ecc-bdd8-4210d5d4747c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
