<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Patra Logistik</name>
   <tag></tag>
   <elementGuidId>8d44520b-445e-4684-8cf0-f64d83bc4e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.main-sidebar-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='sidebar']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;Patra Logistik&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a82ff5bc-9e9d-4feb-899e-22da5acd7256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-sidebar-header</value>
      <webElementGuid>d0afbc20-ac02-476d-8a7c-9805924721f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Patra Logistik</value>
      <webElementGuid>f80edb70-81e9-4d8d-86a6-d795545f761c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar&quot;)/div[@class=&quot;main-sidebar-header&quot;]</value>
      <webElementGuid>26ed3032-e0a7-42c7-aac4-37331214b849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='sidebar']/div</value>
      <webElementGuid>04761a29-3333-40fa-b18b-fe680711e4b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patlog Manajemen'])[1]/following::div[1]</value>
      <webElementGuid>474ad741-9a68-4e04-b91f-862fae5b0775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::div[5]</value>
      <webElementGuid>008ce73e-c2e0-4e85-a507-cd3cd2f6769a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>1df242ec-d8ef-426b-9fd9-ae5d485313e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div</value>
      <webElementGuid>1c70cdb8-b0a2-47cd-9259-36f49053306a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Patra Logistik' or . = ' Patra Logistik')]</value>
      <webElementGuid>a6af2698-2523-4d33-bb21-a3ad928161ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
