<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_PERTASHOP_ri-filter-line position-absolut_40416e</name>
   <tag></tag>
   <elementGuidId>d7bd0033-5676-4f32-969d-4bc6bb95af22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ri-filter-line.position-absolute.top-50.end-0.translate-middle-y.me-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ri-filter-line</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cf2e6660-972a-4795-89f6-307b394f2fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-filter-line position-absolute top-50 end-0 translate-middle-y me-3</value>
      <webElementGuid>bcbe9418-46d7-47a6-9597-c1b3535af23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page&quot;]/div[@class=&quot;main-content app-content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;d-flex gap-3 mb-3&quot;]/div[@class=&quot;form-group position-relative&quot;]/i[@class=&quot;ri-filter-line position-absolute top-50 end-0 translate-middle-y me-3&quot;]</value>
      <webElementGuid>fd67ff2d-006a-4bea-9c0b-b8501883e47b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/i</value>
      <webElementGuid>40495365-455a-44f2-8934-578051c14eae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
