<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TNI Jabar Banten_client</name>
   <tag></tag>
   <elementGuidId>6d64c445-6c4e-4ce5-bc70-87ca1ff4422a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#client-checkbox-77</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='client-checkbox-77']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;TNI Jakarta&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>663eaa1d-3ffd-49b0-8b61-1f2b37ba6843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>84390f6c-baed-4f40-8686-b86677592e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>client-checkbox-77</value>
      <webElementGuid>5b08f6da-7b01-490e-963d-3e91b19a4305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1283cca8-2bb6-43bc-83ba-927954d42ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client</value>
      <webElementGuid>43c6c640-5a38-4d0e-8be2-7c891c04cf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tni</value>
      <webElementGuid>4165d5ad-7595-4a27-95e9-d87067aed508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;client-checkbox-77&quot;)</value>
      <webElementGuid>1ade54d2-85a8-4936-b382-dabab8a491ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='client-checkbox-77']</value>
      <webElementGuid>55a2950d-e1e1-432d-b13e-ba1befb65b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[78]/div/input</value>
      <webElementGuid>bb25a82d-2879-446c-9f8a-439dce8ea34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'client-checkbox-77' and @type = 'checkbox' and @name = 'client']</value>
      <webElementGuid>2edd6021-46d5-483b-a0c0-083e250a6d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
