<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VHS_dateSelect</name>
   <tag></tag>
   <elementGuidId>e7dae751-8a3f-4db5-bcfe-092deef1ee59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateSelect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateSelect']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Date range picker&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d854ac8-3517-4d98-a765-e3af05e8b022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date flatpickr-input active</value>
      <webElementGuid>1a1be744-ad6a-4e64-95c4-d2b876fad8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateSelect</value>
      <webElementGuid>988a77a3-2bdc-453a-8702-9a01868dbac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9d6f2be-23db-4995-954e-8368632a9e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date range picker</value>
      <webElementGuid>7143ac82-ff87-411c-ab9e-563ea37b5933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>231cc476-76d8-4f95-8726-a818f05afdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateSelect&quot;)</value>
      <webElementGuid>66a9449d-c9eb-4978-98b3-2e0d84eee5b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateSelect']</value>
      <webElementGuid>8e698834-7207-424f-b34b-4fc089ef988f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>9f53100e-5698-4a0a-85ca-09a0429ac63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dateSelect' and @type = 'text' and @placeholder = 'Date range picker']</value>
      <webElementGuid>e0258056-2005-4022-9e3d-f540b4ae4eeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
