<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_4.339,44</name>
   <tag></tag>
   <elementGuidId>bb83c7d4-d39e-403c-97f4-5e963f553824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dataTable']/tbody/tr[4]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;4.339,44&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9c003fe2-c438-487c-bb0a-e33a140c9cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4.339,44</value>
      <webElementGuid>01cc3819-f0c4-496f-8532-a9692dc4fb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataTable&quot;)/tbody[1]/tr[4]/td[2]</value>
      <webElementGuid>6fe5c2b5-17e2-4bba-8a8d-73061e7df941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dataTable']/tbody/tr[4]/td[2]</value>
      <webElementGuid>370962fa-6552-422b-a53e-52694710d91b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAWA TIMUR'])[1]/following::td[1]</value>
      <webElementGuid>cb0ea366-334d-477b-9f30-47708f79b791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PLN NUSANTARA-POWER'])[1]/following::td[4]</value>
      <webElementGuid>db1a24a5-7c8f-470c-a387-26e71ba81cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IRT SURALAYA-PLTU'])[1]/preceding::td[2]</value>
      <webElementGuid>f3f034f3-04ba-4b7a-8340-0894b9725790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 5 of 47 entries'])[1]/preceding::td[5]</value>
      <webElementGuid>f5915781-0235-40b5-803e-78ba3d57ab3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4.339,44']/parent::*</value>
      <webElementGuid>71b7e942-45c6-4445-afda-64b9b397707b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]</value>
      <webElementGuid>d89c35bb-0ad8-4e75-b9ed-f90141fa8de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '4.339,44' or . = '4.339,44')]</value>
      <webElementGuid>efc3a2f1-dba1-4ae9-a155-1366ec78a4ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
