<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Overview Bulan Januari 2025_input-group-text</name>
   <tag></tag>
   <elementGuidId>e608a8e8-89f9-43ed-ab7d-a551502c1bcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-group-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview Bulan Januari 2025'])[1]/following::div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.input-group-text</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2cfba4f9-277a-470e-b252-e459e87548fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text</value>
      <webElementGuid>0c5270d0-813f-4318-af49-a5e27bac0b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page&quot;]/div[@class=&quot;main-content app-content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;d-flex d-block gap-2 justify-content-between page-header-breadcumb my-4&quot;]/div[2]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-text&quot;]</value>
      <webElementGuid>d5530bdf-e481-42d2-a89e-11b81fe13ee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overview Bulan Januari 2025'])[1]/following::div[3]</value>
      <webElementGuid>149b18ca-7596-4e07-99ec-b90a0a90803f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyaluran'])[1]/following::div[13]</value>
      <webElementGuid>dd8d8971-049f-422d-aef5-b59d452b08dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proyeksi Pendapatan'])[1]/preceding::div[1]</value>
      <webElementGuid>0ec90532-a5ab-4ef0-a163-54b6595667e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 4.756.126.320'])[1]/preceding::div[4]</value>
      <webElementGuid>6c689953-96b7-4bad-b242-8fed11fee25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div</value>
      <webElementGuid>9fb2debb-2631-430c-9607-4bc6a581786a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
