<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Overview Bulan Januari 2025_dateFilter</name>
   <tag></tag>
   <elementGuidId>4f619740-2716-4f62-a901-f9608245eb85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Pilih Tanggal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91b829c7-1c21-45ae-b278-766fd6df859d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date flatpickr-input active</value>
      <webElementGuid>4f7a7f87-1adb-4123-b57b-8d71663fe0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateFilter</value>
      <webElementGuid>4e8146a7-fccb-449d-8ddc-b0551a9992d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00ea2593-4f2f-4374-b958-a3d36234f6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Tanggal</value>
      <webElementGuid>eefaaf12-9478-45d1-a942-69a4a37d82b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>0c2f0bf5-49cf-4b2b-be28-0350ffe8bc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateFilter&quot;)</value>
      <webElementGuid>4b868319-a6a5-436a-8347-d252c7f23c48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateFilter']</value>
      <webElementGuid>e05b2ef3-aa24-45fd-a40f-a00f766cf5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>667d375d-0857-4f78-bea5-4d4667a45d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dateFilter' and @type = 'text' and @placeholder = 'Pilih Tanggal']</value>
      <webElementGuid>b3753028-d411-4267-890c-260040d872f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
