<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Overview Bulan Januari 2025_dateFilter (1)</name>
   <tag></tag>
   <elementGuidId>bd9665cf-f31a-41e9-bc8d-c18e27d3d419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dateFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Pilih Tanggal&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05afeae1-4db9-4a9a-8ada-cc323fab3421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control date flatpickr-input active</value>
      <webElementGuid>1f57752f-e214-4ee7-b625-435a69b987ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateFilter</value>
      <webElementGuid>8e6602e7-647d-4e85-84e5-a5eac1a7aa04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ae552cf-044f-4fa3-875b-16618bc08a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Tanggal</value>
      <webElementGuid>95fd1d6a-dbef-43c2-82c1-c2d52d409fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>145e692d-28ee-458f-a35e-e971dc874165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateFilter&quot;)</value>
      <webElementGuid>67b9de42-40c9-4238-b10b-6ba9a83fad9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateFilter']</value>
      <webElementGuid>20bfdb34-fee8-4014-a141-e90d22919ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>08775f39-9092-489d-a6da-217193956de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dateFilter' and @type = 'text' and @placeholder = 'Pilih Tanggal']</value>
      <webElementGuid>bc313e9e-6fdd-4009-8d7e-3fa8de007ef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
